#!/usr/bin/env python3
"""R74-b: OpenCC 字典 → internal/t2s 生成物(一次性溯源脚本)。

输入(同目录, 原始数据随库留存佐证溯源):
  TSCharacters.txt / TSPhrases.txt
  来源: https://raw.githubusercontent.com/BYVoid/OpenCC/master/data/dictionary/
  拉取: 2026-09-27 (OpenCC master)

规则(与 R73「宁缺勿错」架构对齐):
  1. 多候选取**第一候选** —— OpenCC 转换默认行为; 歧义词组由 TSPhrases 恒等
     保护词组在词组臂拦截(乾隆|乾坤/鍾繇|魏徵/瞭望/束脩/想像…), 语义一致。
  2. 单字表剔除恒等对(k==v): 行为零差异, 且保住简体文本快速路径(零分配)。
     歧义字 藉/瞭/覆/么 在标准表第一候选即恒等 —— 「宁缺勿错」自动满足;
     乾 第一候选为 干, 由 TSPhrases 乾隆/乾坤/乾元/乾卦/乾陵/畢昇 等 14+ 条
     保护, 与 R73 手工决策(乾→干+词组保护)一致, 保留。
  3. 词组表**保留恒等对**(= 保护词组, 词组臂命中即原样输出=拦截单字臂误转)。
  4. 词组 key rune 长度 > maxPhraseLen(6) 过滤(4 条: 敦煌学名著名句引文,
     正文出现概率≈0, 清单见生成文件头注)。
  5. key/value 全 CJK 校验(词组臂字节下界与 build() 过滤口径安全前提)。

用法: python3 gen_opencc_dict.py  (在 testdata 目录内运行, 覆盖生成 ../dict_*_gen.go)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, ".."))

# 单字表人工剔除清单(任务主任务1: 表中若存在歧义字对按宁缺勿错人工剔除)。
# 实测 OpenCC TSCharacters 第一候选口径下无需剔除 —— 藉/瞭/覆/么 恒等,
# 乾→干 有 TSPhrases 保护词组(与 R73 一致)。留空+机制留档。
CHAR_EXCLUDE = set()

PHRASE_MAX_LEN = 6  # 与 t2s.go maxPhraseLen 同步


def load(fn):
    rows = []
    with open(os.path.join(HERE, fn), encoding="utf-8") as f:
        for ln in f:
            ln = ln.rstrip("\n")
            if not ln or ln.startswith("#"):
                continue
            k, v = ln.split("\t")
            rows.append((k, v.split(" ")))
    return rows


def is_cjk(s):
    return all(
        0x2E00 <= ord(c) <= 0x9FFF or 0x3400 <= ord(c) <= 0x4DBF
        or 0xF900 <= ord(c) <= 0xFAFF or ord(c) >= 0x20000
        for c in s
    )


def gen_chars():
    rows = load("TSCharacters.txt")
    pairs, n_ident, n_multi = [], 0, 0
    seen = set()
    for k, vs in rows:
        v = vs[0]
        if len(vs) > 1:
            n_multi += 1
        if len(v) != 1 or not is_cjk(k) or not is_cjk(v):
            continue
        if k == v:
            n_ident += 1
            continue
        if k in CHAR_EXCLUDE:
            continue
        if k in seen:
            continue  # 原始表 key 唯一, 防御
        seen.add(k)
        pairs.append((k, v))
    pairs.sort()
    return pairs, len(rows), n_ident, n_multi


def gen_phrases():
    rows = load("TSPhrases.txt")
    pairs, dropped_long = [], []
    seen = set()
    for k, vs in rows:
        v = vs[0]
        if not is_cjk(k) or not is_cjk(v) or "|" in k or "|" in v:
            continue
        if len(k) > PHRASE_MAX_LEN:
            dropped_long.append((k, v))
            continue
        if k in seen:
            continue
        seen.add(k)
        pairs.append((k, v))
    pairs.sort()
    return pairs, dropped_long


def emit_go(path, var, comment, items, fmt):
    lines = [
        "// Code generated by testdata/gen_opencc_dict.py; DO NOT EDIT.",
        "// 来源: OpenCC master data/dictionary (2026-09-27 拉取, 原始文件在 testdata/)。",
        "// 规则: 多候选取第一候选(OpenCC 默认转换行为);" + comment,
    ]
    body = ", ".join(fmt.format(k=k, v=v) for k, v in items)
    # 按 ~24 项一行切
    chunks, cur, cur_len = [], [], 0
    for it in items:
        tok = fmt.format(k=it[0], v=it[1]) + ","
        if cur_len + len(tok.encode("utf-8")) > 90 and cur:
            chunks.append("".join(cur))
            cur, cur_len = [], 0
        cur.append(tok)
        cur_len += len(tok.encode("utf-8"))
    if cur:
        chunks.append("".join(cur))
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
        f.write("\n\npackage t2s\n\n")
        f.write('const %s = "" +\n' % var)
        for i, ch in enumerate(chunks):
            tail = " +" if i < len(chunks) - 1 else ""
            f.write('\t"%s"%s\n' % (ch, tail))
    return len(items)


def main():
    cp, n_rows, n_ident, n_multi = gen_chars()
    pp, dropped = gen_phrases()
    cmt_c = " 剔除恒等对(%d, 行为零差异且保简体快速路径); 1→1 保证(%d 原始行, %d 多候选取首)。" % (n_ident, n_rows, n_multi)
    cmt_p = " 词组恒等对保留(=保护词组, 词组臂拦截单字误转); >%d 字词组过滤(%d 条: %s)。" % (
        PHRASE_MAX_LEN, len(dropped), "; ".join("%s→%s" % (k, v) for k, v in dropped))
    n1 = emit_go(os.path.join(OUT, "dict_tschars_gen.go"), "openccCharPairs", cmt_c, cp, "{k}{v}")
    n2 = emit_go(os.path.join(OUT, "dict_tsphrases_gen.go"), "openccPhrasePairs", cmt_p, pp, "{k}|{v}")
    print("chars: %d pairs; phrases: %d pairs; dropped_long: %d" % (n1, n2, len(dropped)))
    for k, v in dropped:
        print("  filtered>6:", k, "->", v)


if __name__ == "__main__":
    sys.exit(main())
